// build.rs — generates the migration registry at compile time.
//
// The registry is derived from the contents of `migrations/` rather than being
// hand-maintained in Rust, so dropping a new versioned SQL file in is all that
// is required to ship a schema change. Two mistakes are turned into compile
// errors instead of silent no-ops: a file that does not follow the
// `V<version>__<description>.sql` convention, and two files claiming the same
// version.

use std::collections::HashSet;
use std::env;
use std::fs;
use std::path::Path;

const MIGRATIONS_DIR: &str = "migrations";
const GENERATED_FILE: &str = "tellus_migrations.rs";

fn main() {
    let manifest_dir =
        env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is always set by cargo");
    let migrations_dir = Path::new(&manifest_dir).join(MIGRATIONS_DIR);

    // Re-run when a file is added, removed or edited. The directory itself is
    // tracked as well, because adding a new file does not otherwise invalidate
    // the cached build script output.
    println!("cargo:rerun-if-changed={MIGRATIONS_DIR}");

    let entries = fs::read_dir(&migrations_dir).unwrap_or_else(|error| {
        panic!(
            "failed to read {}: {error}. Schema migrations belong in that directory.",
            migrations_dir.display()
        )
    });

    let mut discovered: Vec<(u64, String)> = Vec::new();
    let mut claimed_versions: HashSet<u64> = HashSet::new();

    for entry in entries {
        let path = entry
            .expect("failed to read a migrations/ directory entry")
            .path();
        if !path.is_file() {
            continue;
        }
        let Some(file_name) = path.file_name().and_then(|name| name.to_str()) else {
            continue;
        };

        // Hidden files such as `.gitkeep` are tooling noise; anything else that
        // is not versioned SQL is a probable typo worth surfacing, because an
        // unrecognised migration is exactly the kind of file that silently
        // never runs.
        if !file_name.ends_with(".sql") {
            if !file_name.starts_with('.') {
                println!(
                    "cargo:warning=ignoring {MIGRATIONS_DIR}/{file_name}: not a versioned migration \
                     (expected {MIGRATIONS_DIR}/V<version>__<description>.sql)"
                );
            }
            continue;
        }

        let version = parse_migration_name(file_name);
        if !claimed_versions.insert(version) {
            panic!(
                "duplicate migration version V{version}: {MIGRATIONS_DIR}/{file_name} reuses a \
                 version that another file already claims. Versions must be unique and ascending."
            );
        }

        println!("cargo:rerun-if-changed={MIGRATIONS_DIR}/{file_name}");
        discovered.push((version, file_name.to_string()));
    }

    if discovered.is_empty() {
        panic!(
            "no migrations found in {}. Expected at least one {MIGRATIONS_DIR}/V1__*.sql file.",
            migrations_dir.display()
        );
    }
    // Ordering is by parsed version, not filename: `V10__x.sql` sorts before
    // `V2__x.sql` lexicographically, which would apply migrations out of order.
    discovered.sort_by_key(|(version, _)| *version);

    let mut generated = String::from(
        "// @generated by build.rs from the migrations/ directory — do not edit by hand.\n\
         //\n\
         // Regenerated on every build; run `cargo build` after adding a migration.\n\n",
    );
    generated.push_str(
        "/// Every versioned migration in `migrations/`, in ascending version order.\n\
         ///\n\
         /// The SQL is embedded with `include_str!` so a deployed binary never depends on the\n\
         /// `migrations/` directory existing at runtime.\n",
    );
    generated.push_str("pub const MIGRATIONS: &[(&str, &str)] = &[\n");
    for (_, file_name) in &discovered {
        let name = file_name
            .strip_suffix(".sql")
            .expect("extension was checked above");
        generated.push_str(&format!(
            "    (\n        \"{name}\",\n        include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{MIGRATIONS_DIR}/{file_name}\")),\n    ),\n"
        ));
    }
    generated.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is always set by cargo");
    let out_path = Path::new(&out_dir).join(GENERATED_FILE);
    fs::write(&out_path, generated).unwrap_or_else(|error| {
        panic!(
            "failed to write the generated migration registry to {}: {error}",
            out_path.display()
        )
    });
}

/// Extracts the version from a `V<version>__<description>.sql` file name.
///
/// Panics with an actionable message when the convention is not followed, which
/// surfaces as a build failure rather than a migration that never runs.
fn parse_migration_name(file_name: &str) -> u64 {
    let stem = file_name
        .strip_suffix(".sql")
        .expect("caller checked the .sql extension");

    let without_prefix = stem.strip_prefix('V').unwrap_or_else(|| {
        panic!(
            "migration file {MIGRATIONS_DIR}/{file_name} must start with `V<version>`, \
             e.g. `V2__add_light_sensor.sql`"
        )
    });

    let (version_text, description) = without_prefix.split_once("__").unwrap_or_else(|| {
        panic!(
            "migration file {MIGRATIONS_DIR}/{file_name} must use the \
             `V<version>__<description>.sql` naming convention"
        )
    });

    if description.is_empty() {
        panic!("migration file {MIGRATIONS_DIR}/{file_name} is missing a description after `__`");
    }

    version_text.parse().unwrap_or_else(|_| {
        panic!(
            "migration file {MIGRATIONS_DIR}/{file_name} has a non-numeric version \
             `{version_text}`"
        )
    })
}
