// migrations.rs

use libsql::Connection;
use log::debug;

// Generated by `build.rs` from the contents of `migrations/`. Adding a new
// versioned SQL file is all that is required to ship a schema change — there is
// no hand-maintained list to forget to update.
include!(concat!(env!("OUT_DIR"), "/tellus_migrations.rs"));

/// Ledger of migrations that have already been applied to this database.
///
/// The leading underscore marks it as internal bookkeeping so it cannot be
/// confused with a domain table when browsing the schema. SQLite cannot bind
/// identifiers, so the name is interpolated rather than parameterised.
const MIGRATIONS_TABLE: &str = "_migrations";

/// Applies every discovered migration that has not yet been recorded.
pub async fn run_migrations(conn: &Connection) -> Result<(), Box<dyn std::error::Error>> {
    apply_migrations(conn, MIGRATIONS).await
}

/// Applies the given `(name, sql)` pairs in order, skipping any already recorded
/// in the ledger.
///
/// Exposed separately from [`run_migrations`] so tests can drive the runner over
/// a controlled set of migrations — including deliberately broken ones — without
/// touching the real `migrations/` directory.
pub async fn apply_migrations(
    conn: &Connection,
    migrations: &[(&str, &str)],
) -> Result<(), Box<dyn std::error::Error>> {
    // The ledger is created outside the migration files themselves: a migration
    // cannot record its own execution before the table exists.
    ensure_ledger_exists(conn).await?;

    for &(name, sql) in migrations {
        if is_applied(conn, name).await? {
            debug!("Skipping already-applied migration: {}", name);
            continue;
        }

        apply_one(conn, name, sql).await?;
    }

    Ok(())
}

/// Applies a single migration and records it, both inside one transaction.
///
/// The transaction is what makes a migration atomic: SQLite makes DDL
/// transactional, so if any statement in the batch fails — or if recording the
/// migration fails — every statement is rolled back and the migration stays
/// pending. That matters because a half-applied migration recorded as pending
/// would be retried on the next boot against a schema that already contains some
/// of its changes, and would then fail forever on statements like a bare
/// `CREATE TABLE`.
///
/// This means migration SQL no longer has to be written idempotently to be safe
/// to retry, but it should still be written that way: a migration that half
/// applies and then gets rolled back cannot be re-run if it also *drops*
/// something the earlier statements relied on.
async fn apply_one(
    conn: &Connection,
    name: &str,
    sql: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    debug!("Applying migration: {}", name);

    let transaction = conn.transaction().await?;

    if let Err(error) = transaction.execute_batch(sql).await {
        // Roll back explicitly rather than relying on drop behaviour, so the
        // failure surfaces as the original error instead of a lock error later.
        let _ = transaction.rollback().await;
        return Err(format!("migration {name} failed and was rolled back: {error}").into());
    }

    // Recording the migration shares the transaction: it can only become
    // "applied" if the schema change it describes actually landed.
    if let Err(error) = transaction
        .execute(
            &format!("INSERT INTO {MIGRATIONS_TABLE} (name) VALUES (?1)"),
            [name],
        )
        .await
    {
        let _ = transaction.rollback().await;
        return Err(
            format!("migration {name} applied but could not be recorded, so it was rolled back: {error}")
                .into(),
        );
    }

    transaction.commit().await?;
    debug!("Applied migration: {}", name);

    Ok(())
}

/// Creates the ledger table if it does not exist yet.
async fn ensure_ledger_exists(conn: &Connection) -> Result<(), libsql::Error> {
    conn.execute(
        &format!(
            "create table if not exists {MIGRATIONS_TABLE} (
                id integer primary key autoincrement,
                name text not null unique,
                applied_at datetime default current_timestamp
            );"
        ),
        (),
    )
    .await?;

    Ok(())
}

/// Reports whether a migration is already recorded in the ledger.
async fn is_applied(conn: &Connection, name: &str) -> Result<bool, Box<dyn std::error::Error>> {
    let count: i64 = conn
        .query(
            &format!("SELECT COUNT(*) FROM {MIGRATIONS_TABLE} WHERE name = ?1"),
            [name],
        )
        .await?
        .next()
        .await?
        .ok_or("the migration ledger query returned no rows")?
        .get(0)?;

    Ok(count > 0)
}
