// models.rs
use axum::{
    Json,
    http::StatusCode,
    response::{IntoResponse, Response},
};
use serde::{Deserialize, Serialize};
use serde_json::json;
use ts_rs::TS;

// sensor reading request model for Deserializing requests
#[derive(Debug, Deserialize)]
pub struct SensorReadingRequest {
    pub node_id: String,
    pub soil_temperature: f64,
    pub soil_moisture: f64,
    pub air_temperature: Option<f64>,
    pub air_humidity: Option<f64>,
    pub light_level: Option<f64>,
}

// response model — TypeScript bindings are auto-generated by ts-rs on `cargo check`
#[derive(Debug, Serialize, TS)]
#[ts(export, export_to = "../frontend/src/types/generated/SensorReading.ts")]
pub struct SensorReadingResponse {
    #[ts(type = "number")]
    pub id: i64,
    pub timestamp: String,
    pub node_id: String,
    pub soil_temperature: f64,
    pub soil_moisture: f64,
    pub air_temperature: Option<f64>,
    pub air_humidity: Option<f64>,
    pub light_level: Option<f64>,
}

// structures for api responses
pub enum ApiResponse {
    Created(SensorReadingResponse),
    Success(Vec<SensorReadingResponse>),
    Error(StatusCode, String),
}

pub enum ApiError {
    BadRequest(String), // Added String to allow custom error messages
    Forbidden,
    Unauthorised,
    InternalServerError(String), // Added String to log or return the internal cause
}

impl IntoResponse for ApiResponse {
    fn into_response(self) -> Response {
        match self {
            Self::Created(data) => (StatusCode::CREATED, Json(data)).into_response(),
            Self::Success(data) => (StatusCode::OK, Json(data)).into_response(),
            Self::Error(status, message) => {
                (status, Json(serde_json::json!({ "error": message }))).into_response()
            }
        }
    }
}

impl IntoResponse for ApiError {
    fn into_response(self) -> Response {
        let (status, error_message) = match self {
            Self::BadRequest(msg) => (StatusCode::BAD_REQUEST, msg),
            Self::Forbidden => (StatusCode::FORBIDDEN, "Access denied".to_string()),
            Self::Unauthorised => (
                StatusCode::UNAUTHORIZED,
                "Missing or invalid credentials".to_string(),
            ),
            Self::InternalServerError(msg) => {
                // In production, you might want to log 'msg' securely and return a generic message to the client
                println!("Internal Server Error: {}", msg);
                (
                    StatusCode::INTERNAL_SERVER_ERROR,
                    "An unexpected error occurred".to_string(),
                )
            }
        };

        // Standardized JSON error response format
        let body = Json(json!({
            "success": false,
            "error": error_message
        }));

        (status, body).into_response()
    }
}
